### ISSUE TITLE
jest-enzyme typescript declaration no longer working in 6.0.3

### ISSUE THREAD

**Issue by disintegrator** [FormidableLabs/enzyme-matchers#252]
cc @astorije

As of 6.0.3, I started getting compile errors

```
components/ui/LineClamp.test.tsx:91:38 - error TS2339: Property 'toHaveProp' does not exist on type 'Matchers<ReactWrapper<HTMLAttributes, any, Component<{}, {}, any>>>'.

91     expect(wrapper.find("Truncate")).toHaveProp("lines", false);
                                        ~~~~~~~~~~


components/ui/Loading/Loading.test.tsx:14:48 - error TS2339: Property 'toExist' does not exist on type 'Matchers<ReactWrapper<HTMLAttributes, any, Component<{}, {}, any>>>'.

14     expect(wrapper.find("[aria-valuenow=20]")).toExist();
                                                  ~~~~~~~
```

It happens due to #245 which adds an import statement to index.d.ts. This turns index.d.ts into a regular module and breaks the ambient declaration of the jest namespace.

See: https://github.com/Microsoft/TypeScript/issues/5506#issuecomment-153254151

I modified the declaration file to look like this:

```ts
/// <reference types="react" />

// import * as Enzyme from 'enzyme';
// ^^^^^^ this is the problem
// declare global {
//    var shallow: typeof Enzyme.shallow;
//    var mount: typeof Enzyme.mount;
//    var render: typeof Enzyme.render;
// }

declare namespace jest {
    interface Matchers<R> {
        toBeChecked(): void;
        toBeDisabled(): void;
        toBeEmptyRender(): void;
        toContainReact(component: React.ReactElement<any>): void;
        toExist(): void;
        toHaveClassName(className: string): void;
        toHaveHTML(html: string): void;
        toHaveProp(propKey: object|string, propValue?: any): void;
        toHaveRef(refName: string): void;
        toHaveState(stateKey: object|string, stateValue?: any): void;
        toHaveStyle(styleKey: object|string, styleValue?: any): void;
        toHaveTagName(tagName: string): void;
        toHaveText(text: string): void;
        toHaveValue(value: any): void;
        toIncludeText(text: string): void;
        toMatchElement(element: React.ReactElement<any>): void;
        toMatchSelector(selector: string): void;
    }
}
```
... and things are back to working

I understand this is effectively reverting #245 but I suspect a bunch of users will face this issue upon upgrading.
It also seems that `jest-enzyme` is not the right place to be declaring these globals since this module is not actually setting `shallow`, `mount`, `render` on `global`. They are being set by `jest-environment-enzyme`. Perhaps that module can have a declaration file to add the three functions on to the global namespace

**Comment by gerardmrk** [comment]
Can confirm am also getting a whole bunch of these errors.
```
TS2339: Property 'toExist' does not exist on type 'Matchers<ShallowWrapper<{}, {}, Component<{}, {}, any>>>'
```

**Comment by nickpapasavvas** [comment]
I have also the same problem. I tried version 6.0.2 and 6.0.1 but still get these errors. I also tried  importing `import "jest-enzyme"` as it is suggested here: https://github.com/FormidableLabs/enzyme-matchers/issues/177#issuecomment-403261476 without success.

**Comment by astorije** [comment]
Sorry I broke the matchers! 🙏🙏
I can confirm that it also broke on our end, and the analysis above makes sense. Thanks for catching this and thoroughly looking into it!

**Comment by mockdeep** [comment]
Just ran into this, too. Is there any workaround until #255 gets merged?

**Comment by blainekasten** [comment]
I’ll do a release first thing Monday

**Comment by mockdeep** [comment]
Hmm, I'm still seeing this issue after upgrading to `6.0.4`:

```
spec/javascript/_common/components/alpha_modal_spec.tsx:16:17 - error TS2339: Property 'toHaveProp' does not exist on type 'Matchers<any>'.

16   expect(modal).toHaveProp('isOpen', true);
```

I tried downgrading to `5.x`, but it happens there, too. Any ideas what I might be missing?

**Comment by blainekasten** [comment]
that type is defined. https://github.com/FormidableLabs/enzyme-matchers/blob/master/packages/jest-enzyme/src/index.d.ts#L12

I would assume that your setup has an issue loading jest-enzyme types.

**Comment by mockdeep** [comment]
I've been gradually converting a codebase to TypeScript and turns out I needed to convert the file where `'jest-enzyme'` was imported as well in order for it to register. Works now!
